services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # Edge service (All AWS services use this port)
    environment:
      - SERVICES=iam,sts,dynamodb,s3
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DYNAMODB_SHARE_DB=1    # Use one DB for all regions (easier for local dev)
    volumes:
      - "./scripts/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"